---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: https://github.com/codedoors/codedoors.github.io-integrator
collections: 
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
